<script>
    // @ts-nocheck

    import { onMount, onDestroy } from 'svelte';
    import { select } from 'd3-selection';
    import { playSound, stopSound } from '$lib/utils/soundEffects';
    import { setSoundHighlight, clearSoundHighlight } from '$lib/state/audio';

    /**
     * @type {'ships' | 'bluewhale' | 'finwhale' | 'humpbackwhale' | 'dolphins' | 'bocaccio' | 'explosions'}
     */
    export let type;
    
    /**
     * @type {string}
     */
    export let status = 'STATUS';
    
    // Define colors for each sound type (matching Animation.svelte)
    const colors = {
        ships: '#E44000',
        explosions: '#FE7C1F',
        bluewhale: '#73CBE9',
        finwhale: '#E5AA00',
        humpbackwhale: '#E656E1',
        dolphins: '#81C995',
        bocaccio: '#9F6FF8',
    };

    
    // Map types to image filenames
    const imageMap = {
        ships: 'ship.png',
        bluewhale: 'blue.png',
        finwhale: 'fin.png',
        humpbackwhale: 'humpback.png',
        dolphins: 'dolphin.png',
        bocaccio: 'boccacio.png',
        explosions: 'explosion.png'
    };
    
    // Map types to display names
    const displayNames = {
        ships: 'Ship',
        bluewhale: 'Blue Whale',
        finwhale: 'Fin Whale',
        humpbackwhale: 'Humpback',
        dolphins: 'Dolphin',
        bocaccio: 'Boccacio',
        explosions: 'Explosion'
    };

    // Species information for tooltips
    const speciesInfo = {
        bluewhale: {
            name: 'Blue Whale',
            scientific: 'Balaenoptera musculus',
            description: 'The blue whale is the largest animal known to have ever lived, with adults reaching lengths of up to 33 meters and weights of up to 200 tons. They are baleen whales that feed on krill and small fish.'
        },
        finwhale: {
            name: 'Fin Whale',
            scientific: 'Balaenoptera physalus',
            description: 'The fin whale is the second-largest living mammal after the blue whale. They are known for their distinctive fin on their back and can reach speeds of up to 47 km/h.'
        },
        humpbackwhale: {
            name: 'Humpback Whale',
            scientific: 'Megaptera novaeangliae',
            description: 'Humpback whales are known for their complex songs and acrobatic displays. They have long pectoral fins and can migrate thousands of kilometers annually.'
        },
        bocaccio: {
            name: 'Bocaccio Rockfish',
            scientific: 'Sebastes paucispinis',
            description: 'The bocaccio is a species of marine fish in the rockfish family. They can live up to 50 years, inhabiting rocky reefs along the Pacific coast.'
        },
        dolphins: {
            name: 'Dolphin',
            scientific: 'Delphinus delphis',
            description: 'Dolphins are highly intelligent marine mammals known for their playful behavior and complex social structures. They use echolocation to navigate and hunt.'
        },
        ships: {
            name: 'Ship Noise',
            scientific: 'Anthropogenic',
            description: 'Noise generated by ships and vessels, which can interfere with marine life communication and navigation.'
        },
        explosions: {
            name: 'Explosions',
            scientific: 'Anthropogenic',
            description: 'Explosions caused by seal bombs, small, hand-thrown pyrotechnic devices that explode underwater to create a loud sonic blast, used by commercial fishers to scare marine mammals like seals and sea lions away from their nets and catch.'
        }
    };

    let tooltipSelection;

    onMount(() => {
        // Tooltip will be created on demand
    });

    onDestroy(() => {
        tooltipSelection?.remove();
        tooltipSelection = null;
    });

    function ensureTooltip() {
        if (tooltipSelection) {
            return tooltipSelection;
        }
        tooltipSelection = select('body')
            .append('div')
            .attr('class', 'legend-tooltip hidden')
            .style('position', 'fixed')
            .style('pointer-events', 'none')
            .style('left', '0px')
            .style('top', '0px');
        return tooltipSelection;
    }

    function moveTooltip(event) {
        const tooltip = ensureTooltip();
        const offset = 14;
        const tooltipWidth = 300; // Approximate width for description
        const viewportWidth = window.innerWidth;

        if (event.clientX + offset + tooltipWidth > viewportWidth) {
            tooltip
                .style('left', `${event.clientX - offset}px`)
                .style('top', `${event.clientY + offset}px`)
                .style('transform', 'translateX(-100%)');
        } else {
            tooltip
                .style('left', `${event.clientX + offset}px`)
                .style('top', `${event.clientY + offset}px`)
                .style('transform', null);
        }
    }

    function showTooltip(event, soundType) {
        const tooltip = ensureTooltip();
        const info = speciesInfo[soundType];
        tooltip
            .classed('hidden', false)
            .html(`<span class="tooltip-name">${info.name}</span><span class="tooltip-scientific">${info.scientific}</span><span class="tooltip-desc">${info.description}</span>`);
        moveTooltip(event);
    }

    function hideTooltip() {
        tooltipSelection?.classed('hidden', true);
    }
    
    $: color = colors[type] || '#999';
    $: imageSrc = `/assets/legend/${imageMap[type]}`;
    $: displayName = displayNames[type] || type;
</script>

<div
    class="legend-item"
    role="button"
    tabindex="0"
    aria-label={`Play ${displayName} sound`}
    on:mouseenter={(event) => { playSound(type); setSoundHighlight(type); showTooltip(event, type); }}
    on:mousemove={moveTooltip}
    on:focus={(event) => { playSound(type); setSoundHighlight(type); showTooltip(event, type); }}
    on:mouseleave={() => { stopSound(type); clearSoundHighlight(); hideTooltip(); }}
    on:blur={() => { stopSound(type); clearSoundHighlight(); hideTooltip(); }}
    on:keydown={(event) => {
        if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault();
            playSound(type);
            setSoundHighlight(type);
        }
    }}
>
    <div class="content">
        <div class="type-name uppercase font-mono text-xs">{displayName}</div>
        <div class="visual">
            <div class="circle" style="background-color: {color};"></div>
            <img src={imageSrc} alt={displayName} class="illustration" />
        </div>
        <div class="status uppercase text-xs">{status}</div>
    </div>
</div>

<style>
    .legend-item {
        display: inline-flex;
        flex-direction: column;
        align-items: center;
        padding: 2rem 0 1rem;
    }
    
    .content {
        display: flex;
        flex-direction: column;
        align-items: center;
        width: 100%;
    }
    
    .visual {
        position: relative;
        width: 100px;
        height: 100px;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    
    .circle {
        position: absolute;
        /* left: 10px; */
        width: 50px;
        height: 50px;
        border-radius: 50%;
        z-index: 0;
    }
    
    .illustration {
        position: relative;
        max-height: 200px;
        object-fit: contain;
        z-index: 1;
        filter: drop-shadow(0 2px 8px rgba(0, 0, 0, 0.1));
    }

    .illustration:hover{
        transform: scale(1.1);
        transition: 0.3s ease;
        cursor: pointer;
    }
    
    .status {
        color: var(--text-secondary);
        opacity: 0.7;
    }

    :global(.legend-tooltip) {
        z-index: 10;
        background: var(--surface-overlay);
        backdrop-filter: blur(12px); /* Blur effect */
        -webkit-backdrop-filter: blur(12px); /* Safari support */
        border: 1px solid var(--border-subtle);
        color: var(--text-primary);
        padding: 0.5rem 0.75rem;
        display: flex;
        flex-direction: column;
        gap: 0.2rem;
        font-size: 0.75rem;
        transition: opacity 0.15s ease;
        opacity: 1;
        max-width: 300px;
        text-transform: none;
    }

    :global(.legend-tooltip.hidden) {
        opacity: 0;
    }

    :global(.tooltip-name) {
        font-weight: 600;
        text-transform: uppercase;
        font-family: var(--font-mono);
    }

    :global(.tooltip-scientific) {
        font-size: 0.7rem;
        text-transform: italic;
        color: var(--text-secondary);
        font-family: var(--font-serif);
    }

    :global(.tooltip-desc) {
        font-size: 0.8rem;
        line-height: 1.4;
    }
</style>
